version: "3.9"

services:
  backend:
    image: ${DOCKER_HUB_REPO}-backend:${IMAGE_TAG}
    build:
      context: ./backend
    restart: always

  frontend:
    image: ${DOCKER_HUB_REPO}-frontend:${IMAGE_TAG}
    build:
      context: ./frontend
    restart: always

