# version: "3.9"

services:
  backend:
    image: ${DOCKER_HUB_REPO}-backend:${IMAGE_TAG:-latest}
    build:
      context: ./Backend
    restart: always
    ports:
      - "8082:8082"

  frontend:
    image: ${DOCKER_HUB_REPO}-frontend:${IMAGE_TAG:-latest}
    build:
      context: ./Frontend
    restart: always
    ports:
      - "3000:3000"
    env_file: "./Frontend/.env"
